---
- hosts: all
  become: true

  tasks:
    - name: Shutdown ubuntu instances only
      ansible.builtin.command: /sbin/shutdown -t now
      when:
       ansible_facts['os_family'] == "Debian"



----------------or(both are correct)

```yaml
---
- hosts: all
  become: true
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Display all gathered facts
      debug:
        var: ansible_facts
    # display all collected facts (as in above task all gathered facts are stored in variable called ansible_facts by default)
    - name: Shutdown Ubuntu instances only
      ansible.builtin.command: /sbin/shutdown -t now
      when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution'] == "Ubuntu"
```

Explanation:
- The `ansible.builtin.setup` task gathers all facts about the host, including OS family and distribution and you can check the output using debug command and itterate through it as per need.
- The `when` condition is updated to check both `os_family` and `distribution` to ensure the task only runs on Ubuntu instances.